---
title: "Milestone #1"
format: html
editor: visual
---

## Project option selection

Scenario 1: Infectious disease outbreak (simulated) in California

## Link to git repository

https://github.com/estherkong/ph251w_group_project

### Question 1: Team's preferred communication method

Team's preferred communication method. Google Chat is the preferred method of communication.


### Question 2: Team's preferred meeting times and frequency

Preferred meeting times: Saturdays and weekday evenings Preferred meeting frequency: Weekly

{r} \# Q2 Teams preferred meeting times and frequency:

# Saturdays and weekday evenings

# weekly

### Question 3: Team's preferred method for tracking progress

Shared document for meeting notes and action items and member assigned to each. Progress tracked by marking action items when completed.

### Question 4: Point person for contacting course facilitators with questions

Whoever is available/has capacity will contact course facilitators. Default person will Carli.

## Group Tasks
