---
title: "Milestone #2"
format: html
editor: visual
---

Pam

summary(sim_novelid_CA\$new_unrecovered)

```{r}

# We can assume that the data source is simulated data of infectious disease cases for each county in California reported from public health agencies and organizations such as county health departments during 2023. 

# Our research question explores if the current outbreak is disproportionately affecting certain demographic or geographic populations to inform departments and agencies how to allocate prevention and treatment resources. 

library(readr)

sim_novelid_CA <- read_csv("https://raw.githubusercontent.com//PHW290/phw251_projectdata/main/scenario_1/sim_novelid_CA.csv")

sim_novelid_CA

unique(sim_novelid_CA$dt_diagnosis)

#Our importing process involves using the proper package to use a function that imports CSV files and locating the file path (or link) of the file on GITHUB.

#Geography
class(sim_novelid_CA$county)
unique(sim_novelid_CA$county)

#Demographics
class(sim_novelid_CA$age_cat)
unique(sim_novelid_CA$age_cat)
class(sim_novelid_CA$sex)
class(sim_novelid_CA$race_ethnicity)
range(sim_novelid_CA$race_ethnicity)
#1 = "White, Non-Hispanic", 2 = "Black, Non-Hispanic", 3 = "American Indian or Alaska Native, Non-Hispanic", 4 = "Asian, Non-Hispanic", 5 = "Native Hawaiian or Pacific Islander, Non-Hispanic", 6 = "Multiracial (two or more of above races), Non-Hispanic", 7 = "Hispanic (any race)", 9 = "Unknown). No Unknowns then. 

class(sim_novelid_CA$dt_diagnosis)

class(sim_novelid_CA$time_int)
summary(sim_novelid_CA$time_int)

class(sim_novelid_CA$new_infections)
summary(sim_novelid_CA$new_infections)
class(sim_novelid_CA$cumulative_infected)
summary(sim_novelid_CA$cumulative_infected)

#Newly identified individuals having severe disease requiring hospitalization
class(sim_novelid_CA$new_severe)
summary(sim_novelid_CA$new_infections)

#Cumulative number of identified individuals having severe disease requiring hospitalization
class(sim_novelid_CA$cumulative_severe)
summary(sim_novelid_CA$cumulative_severe)

# We might need to convert county, age_cat, sex, race_ethnicity from character into something else if we are going to do a regression later, for example, to compare them with new_infections, cumulative_infected, etc. I am not sure about this one. 

```

You can add options to executable code like this

```{r Esther's chunk'}
library(tidyverse)

filepath_ca_pop_2023 <- "https://raw.githubusercontent.com//PHW290/phw251_projectdata/main/scenario_1/ca_pop_2023.csv"

ca_pop_2023 <- read_csv(filepath_ca_pop_2023)

head(ca_pop_2023)
```

### Carli

```{r}

#Description of the dataset:
# This is a simulated dataset containing reported cases of a disease categorized by date of diagnoses, patient demographics, and cumulative totals for infected, unrecovered, and severe cases, for the county of Los Angelos.  

#Relation of data to problem statement:
# The data provides patient demogrpahics of age group, binary gender, race and ethnicity which will help to answer if there are disparities in the rate of infection among different populations. 

# The dataset was imported using read.csv from the class github and assigned to an object
novelid_LAcounty <- read.csv(
  "https://raw.githubusercontent.com//PHW290/phw251_projectdata/main/scenario_1/sim_novelid_LACounty.csv")

novelid_LAcounty

# Column names were updated to lower case below and reassigned to a new object
la_county_cases <- novelid_LAcounty
names(la_county_cases) <- tolower(names(la_county_cases))

names(la_county_cases)

#Understanding the range of severe cases in each demographic area would be useful. Before we can get the ranges, we need to determine the data types

str(la_county_cases)
# the data elements are all classified as they should be

# We need to know the different race/ethnicity groups in the dataset
unique(la_county_cases$race_eth)

# This gives us "White, Non-Hispanic", "Black, Non-Hispanic", "American Indian or Alaska Native, Non-Hispanic", "Asian, Non-Hispanic", "Native Hawaiian or Pacific Islander, Non-Hispanic", "Multiracial (two or more of above races), Non-Hispanic" and "Hispanic (any race)"

# Then we can summarize each grouping to get the number of cases per group and the range and average of new severe cases.

la_county_cases %>% group_by(
  race_eth) %>%
  summarise(
    count = n(),
    severe_new_min = min(severe_new, na.rm = T),
    severe_new_max = max(severe_new, na.rm = T),
    severe_new_mean = mean(severe_new, na.rm = T),
    severe_cumulative_mean = mean(severe_cumulative, na.rm = T)
)

# It would be a good idea to remove the column dt_report as part of cleaning as this column only contains NA values. 
```
